Repository element-hq/element-desktop, pull requests merged in 2022-01, with the labels that each got.

#295 Fix open button for downloads not working due to ipc filtering
  src/preload.ts
Labels: X-Release-Blocker

#294 Update linting plugin
  hak/matrix-seshat/build.ts
  hak/matrix-seshat/fetchDeps.ts
  package.json
  scripts/fetch-package.js
  scripts/hak/clean.ts
  scripts/hak/copy.ts
  scripts/hak/fetch.ts
  scripts/hak/fetchDeps.ts
  scripts/hak/hakEnv.ts
  scripts/hak/index.ts
  scripts/hak/link.ts
  src/language-helper.ts
  src/tray.ts
  src/vectormenu.ts
  src/webcontents-handler.ts
  yarn.lock
Labels: T-Task

#296 Fix git protocol usage for CI
  scripts/fetchdep.sh
Labels: T-Task

#299 Upgrade to Electron 16
  package.json
  yarn.lock
Labels: T-Defect

#300 Yarn upgrade
  yarn.lock
Labels: T-Task

#298 Disable Git interactive auth when fetching deps
  scripts/fetchdep.sh
Labels: T-Task

#301 Use published matrix-web-i18n
  package.json
  yarn.lock
Labels: T-Task

#303 Upgrade docker image to bionic
  dockerbuild/Dockerfile
Labels: T-Task

#308 Upgrade to electron 16.0.7
  package.json
  yarn.lock
Labels: T-Task

#311 Downgrade to electron 15
  package.json
  yarn.lock
Labels: T-Task

#312 "Show/Hide" tray action shows window from background instead of hiding it.
  src/tray.ts
Labels: T-Enhancement

#313 Yarn upgrade
  yarn.lock
Labels: T-Task
