Repository element-hq/element-desktop, pull requests merged in 2022-06, with the labels that each got.

#372 Upgrade to Electron 19
  package.json
  yarn.lock
Labels: T-Defect

#373 Add CI to improve experience for community
  .github/workflows/pull_request.yaml
Labels: T-Task

#374 Pass missing ci secret
  .github/workflows/pull_request.yaml
Labels: T-Task

#350 Make video rooms opt-out on Nightly
  element.io/nightly/config.json
Labels: T-Task

#376 Support compilation on more Linux targets
  package.json
  scripts/hak/target.ts
  yarn.lock
Labels: Z-Community-PR, T-Enhancement

#375 Abstract electron settings properly to avoid boilerplate-hell
  src/electron-main.ts
Labels: T-Task

#382 Update matrix-web-i18n
  package.json
  yarn.lock
Labels: T-Task

#385 Fix default file name in save-image-as
  src/webcontents-handler.ts
Labels: T-Defect
