Repository element-hq/element-desktop, pull requests merged in 2022-07, with the labels that each got.

#377 Split electron-main into smaller chunks
  package.json
  src/@types/global.d.ts
  src/electron-main.ts
  src/ipc.ts
  src/keytar.ts
  src/seshat.ts
  src/settings.ts
  src/utils.ts
  tsconfig.json
  yarn.lock
Labels: T-Task

#386 Don't check for updates if we already have one downloaded and queued
  src/updater.ts
Labels: T-Defect

#387 Windows MSI package support
  .github/workflows/build.yaml
  package.json
Labels: T-Task

#389 Add a basic PR checklist for all PRs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: T-Task

#388 Fix manual update checks not working after being dismissed
  src/updater.ts
Labels: T-Defect

#379 Add support for disabling spell check
  src/ipc.ts
Labels: T-Enhancement
