Repository element-hq/element-desktop, pull requests merged in 2022-11, with the labels that each got.

#438 Fix macOS builds in GHA
  package.json
  yarn.lock
Labels: T-Task

#434 Add eslint rule unicorn/no-instanceof-array
  package.json
  yarn.lock
Labels: T-Task

#439 Update to @electron/notarize
  package.json
  scripts/electron_afterSign.js
Labels: T-Task

#440 Switch to notarytool
  scripts/electron_afterSign.js
Labels: T-Enhancement

#444 Update to @electron/notarize
  yarn.lock
Labels: T-Task

#450 Update fetch-package.js to use new GHA deployment for develop
  scripts/fetch-package.js
Labels: T-Task

#451 Improve CI stability and tidy it up
  .github/workflows/build.yaml
  .github/workflows/build_linux.yaml
  .github/workflows/build_macos.yaml
  .github/workflows/build_prepare.yaml
  .github/workflows/build_windows.yaml
  test/launch-test.ts
Labels: T-Task

#452 Improve workflow reuse
  .github/workflows/build.yaml
  .github/workflows/build_linux.yaml
  .github/workflows/build_macos.yaml
  .github/workflows/build_prepare.yaml
  .github/workflows/build_windows.yaml
Labels: T-Task

#453 Build Linux to tar.gz
  .github/workflows/build_linux.yaml
  package.json
Labels: T-Task

#459 Downgrade to electron 20.3.4 to fix crash on call hangup
  package.json
  yarn.lock
Labels: T-Defect

#458 Update to Electron 21
  package.json
  yarn.lock
Labels: T-Enhancement

#456 Create packages.element.io directory index scripts
  .github/workflows/packages_index.yaml
  .gitignore
  package.json
  packages.element.io/debian/element-io-archive-keyring.asc
  packages.element.io/debian/element-io-archive-keyring.gpg
  packages.element.io/debian/riot-im-archive-keyring.asc
  packages.element.io/debian/riot-im-archive-keyring.asc.bak
  packages.element.io/debian/riot-im-archive-keyring.gpg
  packages.element.io/debian/riot-im-archive-keyring.gpg.bak
  packages.element.io/element-release-key-2020.asc
  packages.element.io/element-release-key-2020.gpg
  packages.element.io/element-release-key.asc
  packages.element.io/element-release-key.gpg
  packages.element.io/fonts/Inter-Black.woff
  packages.element.io/fonts/Inter-Black.woff2
  packages.element.io/fonts/Inter-BlackItalic.woff
  packages.element.io/fonts/Inter-BlackItalic.woff2
  packages.element.io/fonts/Inter-Bold.woff
  packages.element.io/fonts/Inter-Bold.woff2
  packages.element.io/fonts/Inter-BoldItalic.woff
  packages.element.io/fonts/Inter-BoldItalic.woff2
  packages.element.io/fonts/Inter-ExtraBold.woff
  packages.element.io/fonts/Inter-ExtraBold.woff2
  packages.element.io/fonts/Inter-ExtraBoldItalic.woff
  packages.element.io/fonts/Inter-ExtraBoldItalic.woff2
  packages.element.io/fonts/Inter-ExtraLight.woff
  packages.element.io/fonts/Inter-ExtraLight.woff2
  packages.element.io/fonts/Inter-ExtraLightItalic.woff
  packages.element.io/fonts/Inter-ExtraLightItalic.woff2
  packages.element.io/fonts/Inter-Italic.woff
  packages.element.io/fonts/Inter-Italic.woff2
  packages.element.io/fonts/Inter-Light.woff
  packages.element.io/fonts/Inter-Light.woff2
  packages.element.io/fonts/Inter-LightItalic.woff
  packages.element.io/fonts/Inter-LightItalic.woff2
  packages.element.io/fonts/Inter-Medium.woff
  packages.element.io/fonts/Inter-Medium.woff2
  packages.element.io/fonts/Inter-MediumItalic.woff
  packages.element.io/fonts/Inter-MediumItalic.woff2
  packages.element.io/fonts/Inter-Regular.woff
  packages.element.io/fonts/Inter-Regular.woff2
  packages.element.io/fonts/Inter-SemiBold.woff
  packages.element.io/fonts/Inter-SemiBold.woff2
  packages.element.io/fonts/Inter-SemiBoldItalic.woff
  packages.element.io/fonts/Inter-SemiBoldItalic.woff2
  packages.element.io/fonts/Inter-Thin.woff
  packages.element.io/fonts/Inter-Thin.woff2
  packages.element.io/fonts/Inter-ThinItalic.woff
  packages.element.io/fonts/Inter-ThinItalic.woff2
  packages.element.io/fonts/Inter-italic.var.woff2
  packages.element.io/fonts/Inter-roman.var.woff2
  packages.element.io/fonts/Inter.var.woff2
  packages.element.io/fonts/inter.css
  packages.element.io/logo.svg
  packages.element.io/riot-release-key.asc
  packages.element.io/riot-release-key.gpg
  packages.element.io/styles.css
  scripts/generate-packages-index.ts
  yarn.lock
Labels: T-Task

#464 Update CODEOWNERS
  .github/CODEOWNERS
Labels: T-Task

#457 Enable noImplicitAny and kill off `request`
  package.json
  src/@types/global.d.ts
  src/electron-main.ts
  src/ipc.ts
  src/language-helper.ts
  src/protocol.ts
  src/seshat.ts
  src/settings.ts
  src/tray.ts
  src/vectormenu.ts
  src/webcontents-handler.ts
  tsconfig.json
  yarn.lock
Labels: T-Task
