Repository element-hq/element-desktop, pull requests merged in 2022-05, with the labels that each got.

#351 Iterate CI checks
  .github/workflows/preview_changelog.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/static_analysis.yaml
Labels: T-Task

#348 Allow changing the docker image name for in-docker.sh runs
  scripts/in-docker.sh
Labels: T-Task

#354 Tweak i18n ci rule to ignore RiotTranslateBot
  .github/workflows/static_analysis.yaml
Labels: T-Task

#355 Create dependency upgrade action
  .github/workflows/upgrade_dependencies.yml
Labels: T-Task

#357 Add README badges
  README.md
Labels: T-Task

#358 Make pull_request.yaml between the layers consistent and fix enforce labels
  .github/workflows/pull_request.yaml
Labels: T-Task

#360 Update `weblateToCounterpart` to be more resilient
  scripts/copy-res.js
Labels: X-Release-Blocker, T-Task

#361 Consolidate i18n check into a reusable workflow
  .github/workflows/static_analysis.yaml
Labels: T-Task

#365 Option to disable hardware acceleration
  src/electron-main.ts
Labels: T-Enhancement

#363 Remove stale release.sh parameter for no-jsdoc
  release.sh
Labels: T-Task

#366 Fix gha concurrency conditions
  .github/workflows/pull_request.yaml
Labels: T-Task

#368 Update windows-requirements.md
  docs/windows-requirements.md
Labels: T-Task

#369 Improve hak & build ia32 again by default
  .github/workflows/build.yaml
  scripts/electron_afterSign.js
  scripts/electron_winSign.js
  scripts/hak/copy.ts
  scripts/hak/hakEnv.ts
  scripts/hak/index.ts
  scripts/hak/target.ts
Labels: T-Enhancement

#367 Revert back to using libsqlcipher0 for Debian & Ubuntu packages of Desktop
  .github/workflows/build.yaml
  dockerbuild/Dockerfile
  docs/native-node-modules.md
  element.io/nightly/control.template
  element.io/release/control.template
  hak/matrix-seshat/build.ts
  hak/matrix-seshat/check.ts
  hak/matrix-seshat/fetchDeps.ts
  scripts/hak/hakEnv.ts
Labels: T-Defect

#370 Github Actions pull_request synchronize runs on PR open anyway
  .github/workflows/pull_request.yaml
Labels: T-Task
