Repository element-hq/element-desktop, pull requests merged in 2023-12, with the labels that each got.

#1369 Update org to element-hq in CODEOWNERS
  .github/CODEOWNERS
Labels: T-Task

#1375 Update org in workflows and scripts
  .github/release-drafter.yml
  .github/workflows/build_and_deploy.yaml
  .github/workflows/build_linux.yaml
  .github/workflows/build_prepare.yaml
  .github/workflows/release.yml
  .github/workflows/sync-labels.yml
  .github/workflows/triage-labelled.yml
  scripts/fetch-package.ts
Labels: T-Task, backport staging

#1382 Backport 1375 to staging
  .github/release-drafter.yml
  .github/workflows/build_and_deploy.yaml
  .github/workflows/build_linux.yaml
  .github/workflows/build_prepare.yaml
  .github/workflows/release.yml
  .github/workflows/sync-labels.yml
  .github/workflows/triage-labelled.yml
  scripts/fetch-package.ts
Labels: X-Release-Blocker, T-Task

#1391 Upgrade to glibc 2.28 in the Docker image for Node20 compatibility
  .github/workflows/build_linux.yaml
  dockerbuild/Dockerfile
Labels: T-Deprecation

#1390 Upgrade to {upload,download}-artifact@v4 for better performance
  .github/workflows/build_and_deploy.yaml
  .github/workflows/build_and_test.yaml
  .github/workflows/build_linux.yaml
  .github/workflows/build_macos.yaml
  .github/workflows/build_prepare.yaml
  .github/workflows/build_windows.yaml
Labels: T-Task

#1396 Revert "Upgrade to {upload,download}-artifact@v4 for better performance"
  .github/workflows/build_and_deploy.yaml
  .github/workflows/build_and_test.yaml
  .github/workflows/build_linux.yaml
  .github/workflows/build_macos.yaml
  .github/workflows/build_prepare.yaml
  .github/workflows/build_windows.yaml
Labels: T-Task
