Repository element-hq/element-desktop, pull requests merged in 2023-09, with the labels that each got.

#1193 Updated no drag zones
  src/macos-titlebar.ts
Labels: T-Defect

#1219 Improve edge cases around macOS drag handles
  src/macos-titlebar.ts
Labels: T-Defect

#1226 upgrade electron to 26.2.1 to fix CVE-2023-4863
  package.json
  yarn.lock
Labels: Z-Community-PR, T-Defect

#1194 Enable new room UI by default on nightly
  element.io/nightly/config.json
Labels: T-Task

#1231 Turn off new room header by default
  element.io/nightly/config.json
Labels: T-Task

#1254 Bump electron to 26.2.4
  yarn.lock
Labels: T-Defect, backport staging
