Repository element-hq/element-desktop, pull requests merged in 2023-08, with the labels that each got.

#1136 Restore macOs room header dragability
  src/macos-titlebar.ts
Labels: T-Defect

#1132 Stop using abandoned actions-rs/toolchain action
  .github/workflows/build_macos.yaml
  .github/workflows/build_windows.yaml
Labels: T-Task

#896 Simplify desktop packaging
  .github/workflows/build_and_deploy.yaml
  .github/workflows/build_prepare.yaml
Labels: T-Task

#630 Automatically trigger desktop packages on releases
  .github/workflows/build_and_deploy.yaml
  .github/workflows/build_prepare.yaml
Labels: T-Task

#1163 Add FreeBSD support
  scripts/hak/hakEnv.ts
  scripts/hak/target.ts
Labels: Z-Community-PR, T-Enhancement

#1170 Improve selectors for macos app draggable regions
  src/macos-titlebar.ts
Labels: T-Defect

#1174 Don't intercept Ctrl + Cmd + Q on macOS
  src/electron-main.ts
Labels: Z-Community-PR, T-Defect
