Repository element-hq/element-desktop, pull requests merged in 2023-03, with the labels that each got.

#557 Fix macOS notarisation using keychain credentials
  scripts/electron_afterSign.js
Labels: T-Defect

#555 Guard reprepro db via concurrency limits
  .github/workflows/build_and_deploy.yaml
  .github/workflows/build_linux.yaml
  .github/workflows/reprepro.yaml
Labels: T-Task

#560 Remove items incorrectly included in changelog for 1.11.24
  CHANGELOG.md
Labels: T-Task

#563 Include changelogs in deb package
  .github/workflows/build_and_deploy.yaml
  .github/workflows/build_and_test.yaml
  .github/workflows/build_linux.yaml
  .github/workflows/build_prepare.yaml
  element.io/release/conf_distributions
  scripts/generate-builder-config.ts
Labels: T-Task

#565 Build element-io-archive-keyring package
  .github/workflows/build_keyring.yaml
  element-io-archive-keyring/debian/control
Labels: T-Task

#566 Recommend element-io-archive-keyring from our Debian package
  element.io/nightly/control.template
  element.io/release/control.template
Labels: X-Release-Blocker, T-Enhancement, backport staging

#580 Fix changelog for 1.11.25
  CHANGELOG.md
Labels: T-Task

#581 Fix reprepro test ipv4 vs ipv6
  .github/workflows/reprepro.yaml
Labels: T-Task

#579 Send Electron crashpad reports to Sentry from Nightly
  package.json
  src/electron-main.ts
  test/launch-test.ts
  yarn.lock
Labels: T-Enhancement

#578 Clear electron data when logging out
  package.json
  src/ipc.ts
  yarn.lock
Labels: T-Enhancement

#585 Switch to production ssl.com cert
  .github/workflows/build_windows.yaml
Labels: T-Task

#582 Correctly specify minimum Node version
  docs/windows-requirements.md
  package.json
Labels: T-Task

#183 Show recent room breadcrumbs on touchbar
  src/ipc.ts
Labels: T-Enhancement

#558 Use notarize support built into electron-builder
  .github/workflows/build_macos.yaml
  package.json
  scripts/generate-builder-config.ts
  yarn.lock
Labels: T-Task

#423 Add support for Windows arm64
  .github/workflows/build_and_test.yaml
  .github/workflows/build_windows.yaml
  scripts/hak/target.ts
Labels: T-Task

#587 Iterate ARM support in CI
  .github/workflows/build_and_test.yaml
  .github/workflows/build_linux.yaml
  .github/workflows/build_macos.yaml
  .github/workflows/build_windows.yaml
  hak/matrix-seshat/build.ts
  scripts/hak/target.ts
Labels: T-Task

#588 Switch to live R2 bucket for github actions packaging
  .github/workflows/build_and_deploy.yaml
  .github/workflows/build_prepare.yaml
  .github/workflows/reprepro.yaml
Labels: T-Task

#589 Fix typo in github actions workflow
  .github/workflows/build_and_deploy.yaml
  .github/workflows/packages_index.yaml
Labels: T-Task

#595 Update changelog for v1.11.26 now the security issue is public
  CHANGELOG.md
Labels: T-Task

#586 Remove element-builder specific scripts
  package.json
  scripts/electron_afterSign.js
  scripts/electron_winSign.js
  scripts/generate-builder-config.ts
Labels: T-Task

#598 Automate pushing dockerbuild image to ghcr.io
  .github/workflows/dockerbuild.yaml
  dockerbuild/Dockerfile
Labels: X-Release-Blocker, T-Task

#599 Run build_linux in docker using an older glibc
  .github/workflows/build_linux.yaml
Labels: X-Release-Blocker, T-Defect

#600 Enable gatekeeperAssess
  package.json
Labels: T-Task

#602 Run build_linux in docker using an older glibc (#599)
  .github/workflows/build_linux.yaml
Labels: T-Defect

#605 Use frozen lockfile instead of pure lockfile on yarn install
  .github/workflows/build_and_test.yaml
  .github/workflows/build_linux.yaml
  .github/workflows/build_macos.yaml
  .github/workflows/build_prepare.yaml
  .github/workflows/build_windows.yaml
  .github/workflows/static_analysis.yaml
Labels: T-Task
