Repository element-hq/element-desktop, pull requests merged in 2023-07, with the labels that each got.

#1056 Add fallback `default_server_config` to element.io configs
  element.io/nightly/config.json
  element.io/release/config.json
Labels: T-Task

#1059 Fix Tray icon in Windows forgetting your settings
  package.json
  src/tray.ts
  yarn.lock
Labels: T-Enhancement

#1081 Switch to the new `session` API for screen-sharing
  src/displayMediaCallback.ts
  src/electron-main.ts
  src/ipc.ts
  src/preload.ts
Labels: T-Task

#1099 Avoid using deprecated config.json key casing
  element.io/nightly/config.json
  element.io/release/config.json
Labels: T-Task

#1101 Switch to hidden titleBar on macOS to integrate the app better
  src/electron-main.ts
  src/macos-titlebar.ts
Labels: T-Enhancement

#1120 Fix macos titlebar dragging not blocking the right panel
  src/macos-titlebar.ts
Labels: T-Task

#1126 Fix ability to interact with room topic in header
  src/macos-titlebar.ts
Labels: X-Release-Blocker, T-Defect
