Repository element-hq/element-desktop, pull requests merged in 2023-10, with the labels that each got.

#1259 Bump matrix-web-i18n to 3.1.3 for KEY_SEPARATOR
  package.json
  yarn.lock
Labels: T-Defect

#1272 Implement macos title bar negative space
  src/macos-titlebar.ts
Labels: T-Enhancement

#1274 Update the Element Call unstable URL
  element.io/nightly/config.json
Labels: T-Task

#1273 Write mdbook summary
  docs/SUMMARY.md
Labels: T-Task

#1277 Allow overwriting app.element.io when popping out widgets
  docs/SUMMARY.md
  docs/config.md
  src/webcontents-handler.ts
Labels: T-Enhancement

#1289 Fix Nightly builds not bailing on failure
  .github/workflows/build_and_deploy.yaml
Labels: T-Task

#1291 Fix edge cases around macos draggability
  src/macos-titlebar.ts
Labels: T-Defect
