Repository element-hq/element-desktop, pull requests merged in 2023-04, with the labels that each got.

#601 Use branch specific linux dockerbuild tags
  .github/workflows/build_linux.yaml
Labels: T-Task

#590 Prefer env for passing github context vars
  .github/workflows/build_prepare.yaml
Labels: T-Task

#607 Add grep to dockerbuild image
  dockerbuild/Dockerfile
Labels: T-Task

#606 Fix wrong sqlcipher build being used due to cache conflict
  .github/workflows/build_linux.yaml
Labels: X-Release-Blocker, T-Task

#627 Fix error about webContents on log out
  src/ipc.ts
Labels: T-Defect

#625 Allow testing dockerbuild changes in pull requests
  .github/workflows/build_and_test.yaml
  .github/workflows/build_linux.yaml
Labels: T-Task

#626 Drop rebrand_stub
  .github/workflows/codeql.yml
  build/rebrand_stub/rebrand_stub.c
  build/rebrand_stub/rebrand_stub.exe
  package.json
  scripts/electron_afterPack.js
Labels: T-Task

#629 Workaround Squirrel.Mac wedging app restart after failed update check
  src/updater.ts
Labels: T-Defect

#446 Add support for Linux arm64
  .github/workflows/build_and_deploy.yaml
  .github/workflows/build_and_test.yaml
  .github/workflows/build_linux.yaml
  dockerbuild/Dockerfile
  dockerbuild/aarch64/.cargo/config.toml
  dockerbuild/aarch64/.env
  hak/keytar/build.ts
  hak/matrix-seshat/build.ts
  hak/matrix-seshat/check.ts
Labels: T-Task

#635 Disable blank issues in this repo - they should logged in the element-web repo
  .github/ISSUE_TEMPLATE/config.yml
Labels: T-Task

#631 Use a fully static seshat build
  .github/workflows/build_linux.yaml
  docs/native-node-modules.md
  hak/matrix-seshat/build.ts
  hak/matrix-seshat/check.ts
  hak/matrix-seshat/fetchDeps.ts
  hak/matrix-seshat/hak.json
  hak/matrix-seshat/sqlcipher-4.3.0-win.patch
  package.json
  scripts/hak/README.md
  scripts/hak/hakEnv.ts
  scripts/hak/index.ts
Labels: T-Enhancement

#633 Improve cache busting to consider the build scripts themselves
  .github/workflows/build_linux.yaml
  .github/workflows/build_macos.yaml
  .github/workflows/build_prepare.yaml
  .github/workflows/build_windows.yaml
Labels: T-Task

#632 Make SonarCloud happier about our code quality
  src/squirrelhooks.ts
Labels: T-Task

#895 Start packaging for Debian & Ubuntu aarch64
  .github/workflows/build_and_deploy.yaml
Labels: T-Enhancement
