Repository element-hq/element-desktop, pull requests merged in 2023-05, with the labels that each got.

#944 Fix macos update check exploding
  src/updater.ts
Labels: X-Release-Blocker, T-Defect, backport staging

#947 Print a summary on nightly builds to make versions easier to trace
  .github/workflows/build_prepare.yaml
Labels: T-Task

#948 Null guard global mainWindow better
  src/ipc.ts
  src/seshat.ts
Labels: T-Task

#634 Specify hashes for github actions
  .github/workflows/backport.yml
  .github/workflows/build_macos.yaml
  .github/workflows/build_windows.yaml
Labels: T-Task

#950 Fix wrong version being passed to prepare job
  .github/workflows/build_and_deploy.yaml
Labels: X-Release-Blocker, T-Task, backport staging

#941 Increase timeouts in tests to try and reduce flakiness
  test/launch-test.ts
Labels: T-Task

#952 Update electron-builder
  package.json
  yarn.lock
Labels: dependencies, T-Task

#898 Simplify element builder workflow
  .github/workflows/build_linux.yaml
  element.io/nightly/control.template
  element.io/nightly/riot-nightly_2020071502_all/DEBIAN/control
  element.io/release/control.template
  element.io/release/riot-desktop_1.7.0_all/DEBIAN/control
  package.json
  scripts/generate-builder-config.ts
Labels: T-Task

#960 Update to seshat 3.0.1
  package.json
Labels: T-Defect

#977 Fix accidental change of nightly deb name
  .github/workflows/build_linux.yaml
  scripts/generate-builder-config.ts
Labels: T-Task

#953 Include web bundle hash in nightly summary
  .github/workflows/build_prepare.yaml
Labels: T-Task
