Repository element-hq/element-desktop, pull requests merged in 2024-12, with the labels that each got.

#2025 Fix inability to click on non-logged-in modals on macOS
  src/macos-titlebar.ts
Labels: T-Defect

#2029 Fix secret storage not being used due to bad import
  playwright/e2e/launch/launch.spec.ts
  playwright/snapshots/launch/launch.spec.ts/App-launch-should-launch-and-render-the-welcome-view-successfully-1-linux.png
  playwright/snapshots/launch/launch.spec.ts/App-launch-should-launch-and-render-the-welcome-view-successfully-and-support-seshat-1-linux.png
  src/ipc.ts
  src/keytar.ts
Labels: X-Release-Blocker, T-Defect

#2037 Manal upgrade to prettier 3.4.2
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/SUMMARY.md
  docs/native-node-modules.md
  docs/packaging.md
  docs/windows-requirements.md
  scripts/hak/README.md
  yarn.lock
Labels: T-Enhancement, T-Task
