Repository element-hq/element-desktop, pull requests merged in 2024-04, with the labels that each got.

#1518 Start rolling out rust crypto stack to existing users
  element.io/nightly/config.json
  element.io/release/config.json
Labels: T-Enhancement

#1602 Upgrade electron version
  yarn.lock
Labels: T-Task

#1591 Convert electron-builder config file to TS
  electron-builder.ts
  knip.ts
  package.json
  scripts/hak/hakEnv.ts
  yarn.lock
Labels: T-Task

#1608 Bugfix: Failed to save image
  src/webcontents-handler.ts
Labels: Z-Community-PR, T-Defect

#1587 Re-enable msi perMachine builds
  .github/workflows/build_and_deploy.yaml
  electron-builder.ts
  src/squirrelhooks.ts
  src/updater.ts
Labels: X-Release-Blocker, T-Task

#1628 Update scripts for compatibility with latest NodeJS Security Release
  hak/keytar/build.ts
  scripts/hak/fetch.ts
  scripts/hak/link.ts
  scripts/set-version.ts
Labels: X-Release-Blocker, T-Defect, backport staging

#1635 Enable TAC in nightly config
  element.io/nightly/config.json
Labels: T-Task

#1640 Switch to mapbox-scoped node-pre-gyp package
  package.json
  scripts/@types/node-pre-gyp.d.ts
  scripts/hak/hakEnv.ts
  yarn.lock
Labels: Z-Community-PR, T-Task
