Repository element-hq/element-desktop, pull requests merged in 2024-05, with the labels that each got.

#1650 Roll out Rust crypto to 30% of existing users of stable Element Desktop
  element.io/release/config.json
Labels: T-Enhancement

#1653 Roll back electron to v29
  package.json
  yarn.lock
Labels: T-Defect, T-Task, backport staging

#1662 Add support for io.element.desktop scheme for OIDC
  electron-builder.ts
  src/protocol.ts
Labels: T-Enhancement

#1667 Fix contributing link in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: T-Task

#1665 fix: window focus on notification click
  src/ipc.ts
Labels: Z-Community-PR, T-Defect

#1669 Add glibc check to Linux build
  .github/workflows/build_linux.yaml
  scripts/glibc-check.sh
Labels: T-Enhancement, T-Task

#1668 Improve tests to run on arm64 & smoketest seshat
  .github/workflows/build_and_test.yaml
  playwright/e2e/launch/launch.spec.ts
  playwright/snapshots/launch/launch.spec.ts/App-launch-should-launch-and-render-the-welcome-view-successfully-and-support-seshat-1-linux.png
Labels: T-Enhancement, T-Task

#1664 Distribute aarch64 Linux tarball builds
  .github/workflows/build_and_deploy.yaml
  .github/workflows/build_and_test.yaml
  .github/workflows/build_linux.yaml
  .github/workflows/dockerbuild.yaml
  dockerbuild/Dockerfile
  dockerbuild/aarch64/.cargo/config.toml
  dockerbuild/aarch64/.env
  dockerbuild/setup.sh
  scripts/glibc-check.sh
Labels: T-Enhancement, T-Task

#1680 Fix Linux build docker tag for release builds
  .github/workflows/build_linux.yaml
Labels: X-Release-Blocker, T-Task, backport staging

#1345 Enable new room header by default on nightly
  element.io/nightly/config.json
Labels: T-Task
