Repository element-hq/element-desktop, pull requests merged in 2024-01, with the labels that each got.

#1408 Fix docker commands to work on ARM systems like macOS M1
  package.json
  scripts/in-docker.sh
Labels: T-Task

#1410 Update teams names in CODEOWNERS
  .github/CODEOWNERS
Labels: T-Task

#1402 Move electron-builder config to javascript file
  .github/workflows/build_linux.yaml
  .github/workflows/build_macos.yaml
  .github/workflows/build_windows.yaml
  electron-builder.js
  package.json
  scripts/generate-builder-config.ts
Labels: T-Task

#1411 Switch to artifact-v4 and move packages.element.io packing to deploy workflow
  .github/workflows/build_and_deploy.yaml
  .github/workflows/build_and_test.yaml
  .github/workflows/build_linux.yaml
  .github/workflows/build_macos.yaml
  .github/workflows/build_prepare.yaml
  .github/workflows/build_windows.yaml
Labels: T-Task

#1412 Burn Node-related Electron fuses as a proactive hardening measure
  .github/workflows/build_and_test.yaml
  .github/workflows/build_macos.yaml
  electron-builder.js
  package.json
  yarn.lock
Labels: T-Enhancement, Security

#1434 Fix Element Nightly debian packaging
  electron-builder.js
Labels: X-Release-Blocker, T-Defect

#1440 Run more of the deploy code for pre-releases
  .github/workflows/build_and_deploy.yaml
  .github/workflows/build_prepare.yaml
Labels: T-Task

#1441 Add knip unused code & dependency analyser
  .github/workflows/build_and_test.yaml
  .github/workflows/build_linux.yaml
  .github/workflows/build_macos.yaml
  .github/workflows/build_prepare.yaml
  .github/workflows/build_windows.yaml
  .github/workflows/static_analysis.yaml
  knip.ts
  package.json
  src/language-helper.ts
  yarn.lock
Labels: T-Task

#1413 Force Element Call video rooms
  element.io/nightly/config.json
Labels: T-Task

#1466 Fix development issue on Windows
  src/tray.ts
Labels: T-Task

#1472 Switch to M1 runner for macOS builds
  .github/workflows/build_macos.yaml
Labels: T-Task

#1474 Use powershell shell instead of pwsh
  .github/workflows/build_windows.yaml
Labels: T-Task

#1473 Update Node version in Dockerfile to comply with engine minimum
  dockerbuild/Dockerfile
Labels: T-Task
