Repository element-hq/element-desktop, pull requests merged in 2024-07, with the labels that each got.

#1740 Remove redundant reusable workflow input
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
Labels: T-Task

#1756 remove Libera.Chat bridge from room_directory
  element.io/nightly/config.json
  element.io/release/config.json
Labels: Z-Community-PR, T-Task

#1757 Support authenticated media downloads in Desktop too
  src/electron-main.ts
  src/preload.ts
Labels: T-Enhancement

#1771 Workaround macOS permission issues in Github Actions CI
  .github/workflows/build_and_test.yaml
  playwright.config.ts
Labels: T-Task

#1760 Remove glob workaround
  src/@types/glob.d.ts
Labels: T-Task

#1767 Add self-hosted runner arch sanity check
  .github/workflows/build_and_test.yaml
  .github/workflows/build_linux.yaml
Labels: T-Defect, T-Task

#1779 Fix Docker tooling for building native components
  dockerbuild/Dockerfile
Labels: T-Defect

#1810 Make sonarcloud happier
  dockerbuild/Dockerfile
  playwright/Dockerfile
  scripts/hak/hakEnv.ts
  src/updater.ts
Labels: T-Enhancement, T-Task
