Repository element-hq/element-desktop, pull requests merged in 2024-10, with the labels that each got.

#1896 Remove legacy room header
  element.io/nightly/config.json
  src/macos-titlebar.ts
Labels: T-Task

#1804 Add monochrome tray icon
  res/img/monochrome.ico
  res/img/monochrome.png
  src/@types/global.d.ts
  src/electron-main.ts
  src/settings.ts
  src/tray.ts
Labels: Z-Community-PR, T-Enhancement

#1920 Pin GHA to ubuntu 22
  .github/workflows/backport.yml
  .github/workflows/build_and_deploy.yaml
  .github/workflows/build_and_test.yaml
  .github/workflows/build_linux.yaml
  .github/workflows/build_prepare.yaml
  .github/workflows/dockerbuild.yaml
  .github/workflows/release.yml
  .github/workflows/static_analysis.yaml
  .github/workflows/triage-incoming.yml
Labels: T-Task

#1925 Remove React SDK version from develop build output
  .github/workflows/build_prepare.yaml
Labels: T-Task

#1916 Improve seshat deleteContents
  src/seshat.ts
Labels: T-Defect

#1934 Revert "Add monochrome tray icon"
  res/img/monochrome.ico
  res/img/monochrome.png
  src/@types/global.d.ts
  src/electron-main.ts
  src/settings.ts
  src/tray.ts
Labels: T-Task

#1938 Pin GHA runner versions
  .github/workflows/build_and_test.yaml
  .github/workflows/build_windows.yaml
  docs/windows-requirements.md
Labels: T-Task

#1921 Support specifying the config location manually (outside of the user's profile)
  README.md
  playwright/e2e/launch/config-options.spec.ts
  playwright/element-desktop-test.ts
  playwright/fixtures/custom-config.json
  src/electron-main.ts
Labels: T-Enhancement

#1951 Update way of passing notarization team id to workflow
  .github/workflows/build_macos.yaml
  electron-builder.ts
Labels: T-Task

#1967 Upgrade to glibc2.31 for Linux builds
  .github/workflows/build_linux.yaml
  dockerbuild/Dockerfile
  electron-builder.ts
Labels: T-Enhancement, T-Task

#1325 Wrap up new release workflows
  release_config.yaml
Labels: T-Task

#1970 Prefer native node fetch over node-fetch
  package.json
  scripts/fetch-package.ts
  scripts/tsconfig.json
  src/updater.ts
  src/webcontents-handler.ts
  tsconfig.json
  yarn.lock
Labels: T-Enhancement, T-Task
