Repository element-hq/element-desktop, pull requests merged in 2024-06, with the labels that each got.

#1706 Roll out Rust crypto to 60% of existing users of stable Element Desktop
  element.io/release/config.json
Labels: T-Enhancement

#1001 Switch debs to use the SQLCipher static version
  .github/workflows/build_and_deploy.yaml
  package.json
Labels: T-Defect

#1725 Conform to no-floating-promises
  scripts/fetch-package.ts
  src/electron-main.ts
  src/ipc.ts
  src/macos-titlebar.ts
  src/protocol.ts
  src/squirrelhooks.ts
  src/vectormenu.ts
  src/webcontents-handler.ts
Labels: T-Task

#1731 Tighten macOS entitlements
  build/entitlements.mac.plist
Labels: T-Enhancement

#1732 Remove deprecated packages
  package.json
  scripts/@types/find-npm-prefix.d.ts
  scripts/hak/index.ts
  yarn.lock
Labels: T-Task
