Repository element-hq/element-desktop, pull requests merged in 2024-02, with the labels that each got.

#1475 Reuse release-drafter-workflow from js-sdk
  .github/workflows/release-drafter.yml
Labels: T-Task

#1480 Add waits for post-release steps for improved visibility
  .github/workflows/release.yml
Labels: T-Task

#1502 Update variable-mapper to silence actions warnings
  .github/workflows/build_linux.yaml
  .github/workflows/build_windows.yaml
Labels: T-Task

#1501 Update eSigner CKA
  .github/workflows/build_windows.yaml
Labels: T-Task

#1512 Saner releases clean up
  .github/PULL_REQUEST_TEMPLATE.md
  release.sh
Labels: T-Task

#1519 Improve loading of JSON files to avoid implicit behaviours of Node require
  src/electron-main.ts
  src/language-helper.ts
  src/utils.ts
Labels: T-Defect

#1510 Fix Native OIDC for Element Desktop
  src/protocol.ts
Labels: T-Enhancement

#1527 Fix i18n json file paths
  src/language-helper.ts
Labels: X-Release-Blocker, T-Defect

#1511 Update setup-xvfb action to fix node16 deprecation warning
  .github/workflows/build_and_test.yaml
Labels: T-Task

#1542 PR template: reminder to document your stuff
  .github/PULL_REQUEST_TEMPLATE.md
Labels: T-Task

#1547 Add job to automate adding new issues to the new project
  .github/workflows/triage-incoming.yml
Labels: T-Task

#1545 Prevent "Element" hardcoded in i18n files
  .github/workflows/static_analysis.yaml
  package.json
  yarn.lock
Labels: T-Task
