Repository element-hq/element-desktop, pull requests merged in 2025-09, with the labels that each got.

#2526 Automatically select first source for desktop capture under Wayland
  src/electron-main.ts
Labels: Z-Community-PR, T-Enhancement

#2554 Fix Confirm your identity buttons being unclickable
  src/macos-titlebar.ts
Labels: T-Defect

#2544 Update Electron to v38.1.0 to fix Kernel crash on multi-GPU systems
  package.json
  yarn.lock
Labels: Z-Community-PR, T-Defect
