Repository element-hq/element-desktop, pull requests merged in 2025-02, with the labels that each got.

#1979 Enable fuse EnableEmbeddedAsarIntegrityValidation
  electron-builder.ts
  package.json
Labels: T-Enhancement

#2109 Update package description
  package.json
Labels: T-Task

#2125 Fix hak script import in tsx esm for Windows
  scripts/hak/index.ts
Labels: X-Release-Blocker, T-Task

#2122 Simplify linux builds
  .github/workflows/build_linux.yaml
Labels: T-Task

#2128 Update electron-clear-data to @standardnotes/electron-clear-data
  package.json
  src/ipc.ts
  yarn.lock
Labels: T-Task

#2130 Close stale PRs after 180 days
  .github/workflows/triage-stale.yml
Labels: T-Task

#2131 Test windows signing in CI
  .github/workflows/build_windows.yaml
Labels: T-Task

#2153 Simplify CI workflows
  .github/workflows/build_linux.yaml
  .github/workflows/build_macos.yaml
  .github/workflows/build_windows.yaml
Labels: T-Task

#624 Add support for Windows arm64
  .github/workflows/build_and_deploy.yaml
  .github/workflows/build_and_test.yaml
  .github/workflows/build_windows.yaml
  docs/windows-requirements.md
  package.json
  scripts/cl.bat
Labels: T-Enhancement

#2137 Improve CI test signing & assert expected files
  .github/SSLcom-sandbox.crt
  .github/workflows/build_and_test.yaml
  .github/workflows/build_linux.yaml
  .github/workflows/build_macos.yaml
  .github/workflows/build_windows.yaml
Labels: T-Task

#2158 Fix macOS nightly builds
  .github/workflows/build_macos.yaml
Labels: T-Task

#2168 Specify node version to avoid NAPI keytar bug
  .github/workflows/build_and_test.yaml
  .github/workflows/build_linux.yaml
  .github/workflows/build_macos.yaml
  .github/workflows/build_prepare.yaml
  .github/workflows/build_windows.yaml
  .github/workflows/dockerbuild.yaml
  .node-version
  dockerbuild/Dockerfile
  dockerbuild/setup.sh
  package.json
Labels: T-Defect, T-Task

#2171 Use modern Dockerfile env format to silence warnings
  dockerbuild/Dockerfile
Labels: T-Task

#2173 Make keytar mandatory and build it without hak
  electron-builder.ts
  hak/keytar/build.ts
  hak/keytar/check.ts
  hak/keytar/hak.json
  package.json
  src/@types/keytar.d.ts
  src/electron-main.ts
  src/ipc.ts
  src/keytar.ts
  src/seshat.ts
  yarn.lock
Labels: T-Enhancement, T-Task
