Repository element-hq/element-desktop, pull requests merged in 2025-04, with the labels that each got.

#2225 Remove support for 32 bit / ia32 Windows.
  .github/workflows/build_and_deploy.yaml
  .github/workflows/build_prepare.yaml
  .github/workflows/build_windows.yaml
Labels: T-Deprecation

#2246 Support specifying the profile dir path via env var (#2226)
  src/electron-main.ts
Labels: Z-Community-PR, T-Enhancement

#2248 Add tests for fix to getOidcCallbackUrl
  playwright/e2e/launch/launch.spec.ts
  playwright/e2e/launch/oidc.spec.ts
Labels: T-Task

#2231 Update config logging to specify config file path
  src/electron-main.ts
  src/utils.ts
Labels: Z-Community-PR, T-Enhancement

#2271 Enable windows arm64 tests using `windows-11-arm` runner
  .github/workflows/build_windows.yaml
Labels: T-Task

#2280 Fix `io.element.desktop` protocol handler
  src/protocol.ts
Labels: T-Defect, backport staging

#2282 Improve HTML test report
  .github/workflows/build_and_test.yaml
  .github/workflows/build_linux.yaml
  .github/workflows/build_macos.yaml
  .github/workflows/build_test.yaml
  .github/workflows/build_windows.yaml
  playwright.config.ts
Labels: T-Task

#2275 Notification fixes for Windows - AppID name was messing up handler
  src/electron-main.ts
Labels: Z-Community-PR, T-Defect

#2227 Migrate from keytar to safeStorage
  .github/workflows/build_test.yaml
  playwright/e2e/launch/launch.spec.ts
  playwright/element-desktop-test.ts
  scripts/tsconfig.json
  src/@types/global.d.ts
  src/electron-main.ts
  src/i18n/strings/en_EN.json
  src/ipc.ts
  src/language-helper.ts
  src/seshat.ts
  src/settings.ts
  src/store.ts
Labels: T-Enhancement

#2295 Update copy for the Electron Linux keyring backend error
  src/i18n/strings/en_EN.json
  src/store.ts
Labels: T-Enhancement, T-Task
