Repository element-hq/element-desktop, pull requests merged in 2025-01, with the labels that each got.

#2074 Roll back electron to fix context-menu on macOS
  package.json
  yarn.lock
Labels: T-Defect, T-Task

#2085 Block access to matrix.org so that tests do not flake on its availability
  playwright/element-desktop-test.ts
  playwright/snapshots/launch/launch.spec.ts/App-launch-should-launch-and-render-the-welcome-view-successfully-1-linux.png
Labels: T-Task

#2097 Work around cloudflare R2 / aws client incompatability
  .github/workflows/build_and_deploy.yaml
  .github/workflows/build_prepare.yaml
Labels: T-Defect

#2098 Switch to arm runners instead of self-hosted dind runners
  .github/workflows/build_and_test.yaml
  .github/workflows/build_linux.yaml
Labels: T-Task

#2096 Update Node in dockerbuild environment
  .github/workflows/dockerbuild.yaml
  dockerbuild/Dockerfile
Labels: T-Defect, T-Task

#2106 Update electron-builder and harden fuse configuration
  electron-builder.ts
  package.json
  yarn.lock
Labels: T-Enhancement
