Repository element-hq/element-desktop, pull requests merged in 2025-05, with the labels that each got.

#2299 Notes on using gdb
  docs/SUMMARY.md
  docs/gdb.md
Labels: T-Task

#2298 Revert "Update dependency electron to v36"
  package.json
  yarn.lock
Labels: T-Defect, T-Task

#2306 Re-apply "Update dependency electron to v36"
  package.json
  yarn.lock
Labels: T-Task

#2169 Rely on @electron/universal for macOS ASAR integrity
  electron-builder.ts
  package.json
  yarn.lock
Labels: T-Enhancement, T-Task

#2329 Add branch matching
  .github/workflows/build_and_test.yaml
  .github/workflows/build_prepare.yaml
  scripts/branch-match.sh
  scripts/fetchdep.sh
Labels: T-Task

#2336 Add docs for debugging element desktop
  docs/SUMMARY.md
  docs/debugging.md
Labels: T-Task

#2338 Use `basic_text` as fallback when encryption not available
  src/i18n/strings/en_EN.json
  src/store.ts
Labels: T-Defect, backport staging

#2285 Support build-time specified protocol scheme for oidc callback
  electron-builder.ts
  src/@types/global.d.ts
  src/build-config.ts
  src/electron-main.ts
  src/ipc.ts
  src/preload.cts
  src/protocol.ts
  src/utils.ts
Labels: T-Enhancement

#2341 Enable plain text encryption early if we actually mean to use `basic_text` as backend
  src/store.ts
Labels: T-Defect

#2343 Enable plain text encryption before checking if encryption is available
  src/store.ts
Labels: T-Defect
