Repository element-hq/element-desktop, pull requests merged in 2025-03, with the labels that each got.

#2172 Switch to shiftkey/node-keytar as it has NAPI 10 updates
  .node-version
  knip.ts
  package.json
  src/ipc.ts
  src/seshat.ts
  yarn.lock
Labels: T-Enhancement

#2182 Simplify workflows remove unused parameters
  .github/workflows/build_and_deploy.yaml
  .github/workflows/build_and_test.yaml
  .github/workflows/build_linux.yaml
  .github/workflows/build_prepare.yaml
Labels: T-Task

#2181 Deprecate ia32 Windows builds
  .github/workflows/build_windows.yaml
Labels: T-Task, T-Deprecation

#2210 Fix `--no-update` command line flag
  .github/workflows/build_and_test.yaml
  playwright/e2e/launch/launch.spec.ts
  playwright/element-desktop-test.ts
  src/electron-main.ts
Labels: T-Defect

#2170 Remove temporary awscli s3-r2 workaround
  .github/workflows/build_and_deploy.yaml
  .github/workflows/build_prepare.yaml
Labels: T-Task
